### ISSUE TITLE
remove OAK/enums stuff

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/submission-schema#249]
The makefile targets in https://github.com/microbiomedata/external-metadata-awareness aren't very ergonomic, but they (or some python scripts to be written by @sierra-moxon ) probably have more potential* than the workflows further down in this issue's comments

for example, https://github.com/microbiomedata/external-metadata-awareness/blob/main/Makefiles/soil-env_broad_scale.Makefile

* automation, harmonization between queries and human override

----

## no need to pull semsql files into repo 
_unless the ones in the BBOP S3 bucket don't include really recent changes_

```make
local/envo.db.gz:
	wget https://s3.amazonaws.com/bbop-sqlite/envo.db.gz -O $@

local/envo.db: local/envo.db.gz
	gzip -d $<
```

**Comment by turbomam** [comment]
## was already commented out

```make
#local/alpine_biome_tree_down.txt: local/envo.db
#	$(RUN) runoak \
#		-i $< tree \
#		--down \
#		--output $@ \
#		--predicates rdfs:subClassOf 'alpine biome'
#
#local/alpine_biome_pvs.txt: local/alpine_biome_tree_down.txt
#	$(RUN) oak-tree-to-pv-list \
#		--discard-line-pattern 'alpine biome'  \
#		--input-file $< \
#		--output-file $@
```

**Comment by turbomam** [comment]
who, it's been a long time since I ran any of this


```shell
poetry run oak-tree-to-pv-list \
        --discard-line-pattern 'terrestrial biome'  \
        --input-file local/terrestrial_biome_tree_down.txt \
        --output-file local/terrestrial_biome_pvs.txt
```

> ```
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-submission-schema-DC6HKp4p-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-submission-schema-DC6HKp4p-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-submission-schema-DC6HKp4p-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-submission-schema-DC6HKp4p-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/gitrepos/submission-schema/src/nmdc_submission_schema/scripts/oak_tree_to_pv_list.py", line 47, in main
>     code, name = no_ws_line.split(" ! ")
> ValueError: not enough values to unpack (expected 2, got 1)
> ```
>
